### ISSUE TITLE
Docs don't allow text copy.

### ISSUE THREAD

**Issue by wiretail** [haruncpi/laravel-log-reader#1]
The site where you host the docs ( https://laravelarticle.com ) has right click and Ctrl-C disabled with JavaScript. 

This is 100% annoying on a development oriented site, especially documentation (can't even copy the "admin/log-reader" end of URL route), and 0% useful, as it's trivial for any developer (your target audience) to work around by disabling JavaScript (usually one click in the Ad Blocker we already have). 

Please don't resort to tricks like this.  Or at least move the documentation to a page without it, or to GitHub itself if you must do this for your other articles.  But its not protecting anything, and just inspires "composer remove ..." and moving on.  

(Most won't bother with letting you know about it, like this.  I am trying to be helpful.  And the package looks interesting and useful.)

**Comment by haruncpi** [comment]
Dear, This is not package related issue and all code snippet are copyable via clicking copy.
