### ISSUE TITLE
[BUG] won't read custom log names

### ISSUE THREAD

**Issue by robertnicjoo** [haruncpi/laravel-log-reader#12]
If you change log file names in `config/logging.php` then this package won't be able to read the files.

env

```batch
LOG_CHANNEL=daily
```

logging.php

```php
'daily' => [
  'driver' => 'daily',
  'path' => storage_path('logs/whatEver.log'),
  'level' => 'debug',
  'days' => 14,
],
```

**Comment by haruncpi** [comment]
Daily means it parse file name with date (Laravel default behaviour for daily file logging naming convention). Date by date file and list it with a dropdown.

**Comment by robertnicjoo** [comment]
i guess you didn't understand my point.

`If you change log file names` like `whatEver.log` that means file nme not be included date stamp (i.e. laravel.log instead of 2020-05-31-laravel.log` then this package is not able to read the file because log file (name) doesn't have date stamp in it.
