### ISSUE TITLE
Index page breaks when changing API route

### ISSUE THREAD

**Issue by alistairreynolds** [haruncpi/laravel-log-reader#2]
Great package, very useful!

One issue I found is if the API route changes in the config file, it no longer shows any logs. Seems to be due to hard coded routes in the index view

```              
if (date !== '' && date !== undefined) {
    url = '{{url('/admin/api/log-reader')}}?date=' + date
        } else {
    url = '{{url('/admin/api/log-reader')}}'
}
```

**Comment by haruncpi** [comment]
Now it's ok - v1.0.4
